/* ─────────────────────────────────────
   KINETIC ENTERTAINMENT — main.js
   ───────────────────────────────────── */

/* ── Artist Data ── */
const ARTISTS = {
  hanchae: {
    number: '01',
    nameKo: '한채영 (agent)',
    nameEn: 'HAN CHAE YOUNG (agent)',
    photos: [
      PHOTO_DATA["hanchae_1"],
      PHOTO_DATA["hanchae_2"],
      PHOTO_DATA["hanchae_3"],
    ],
    bgClass: 'ac-bg-1',
    specs: [
      { label: '신장', value: '169 cm' },
      { label: '생년', value: '1978년생' },
    ],
    filmo: [
      { year: '2025', title: '악의 도시', platform: '영화' },
      { year: '2024', title: '스캔들', platform: 'KBS2' },
      { year: '2023', title: '엑스오, 키티', platform: 'Netflix' },
      { year: '2021', title: '스폰서', platform: 'MBN' },
      { year: '2018', title: '신과의 약속', platform: 'MBC' },
      { year: '2017', title: '이웃집 스타', platform: '영화' },
      { year: '2013', title: '예쁜남자', platform: 'KBS2' },
      { year: '2013', title: '광고천재 이태백', platform: 'KBS2' },
      { year: '2009', title: '꽃보다 남자', platform: 'KBS2' },
      { year: '2006', title: '불꽃놀이', platform: 'MBC' },
      { year: '2005', title: '온리유', platform: 'SBS' },
      { year: '2005', title: '쾌걸춘향', platform: 'KBS2' },
      { year: '2002', title: '정', platform: 'SBS' },
      { year: '2001', title: '아버지와 아들', platform: 'SBS' },
      { year: '2000', title: '가을동화', platform: 'KBS2' },
    ],
    ads: [
      { year: '2025', title: '광고 활동', platform: 'CF' },
      { year: '2017', title: '광고 활동', platform: 'CF' },
      { year: '2011', title: '빅 딜', platform: '영화' },
      { year: '2010', title: '인플루언스', platform: '영화' },
    ],
  },
  gominseung: {
    number: '02',
    nameKo: '고민승',
    nameEn: 'GO MIN SEUNG',
    photos: [
      PHOTO_DATA["gominseung_1"],
      PHOTO_DATA["gominseung_2"],
      PHOTO_DATA["gominseung_3"],
    ],
    bgClass: 'ac-bg-2',
    specs: [
      { label: '신장', value: '161 cm' },
      { label: '생년', value: '2002년생' },
      { label: '특기', value: '경상도사투리, 수화, 피아노, 한국무용' },
    ],
    filmo: [
      { year: '2026', title: '오늘도 매진했습니다', platform: 'SBS' },
      { year: '2026', title: '참교육', platform: 'Netflix' },
      { year: '2026', title: '엑스오, 키티 시즌3', platform: 'Netflix' },
      { year: '2025', title: '첫번째 남자', platform: 'MBC' },
      { year: '2025', title: '환생걸스 사군자', platform: 'Tving' },
      { year: '2025', title: '사계의봄', platform: 'SBS' },
    ],
    ads: [
      { year: '2026', title: '롯데월드', platform: 'CF' },
      { year: '2025', title: '윤빌리티', platform: 'CF' },
      { year: '2025', title: '또봉이 통닭 웹드라마', platform: 'CF' },
      { year: '2020', title: '60계 치킨', platform: 'CF' },
    ],
  },
  leehyunjeong: {
    number: '03',
    nameKo: '이현정',
    nameEn: 'LEE HYUN JEONG',
    photos: [
      PHOTO_DATA["leehyunjeong_1"],
      PHOTO_DATA["leehyunjeong_2"],
      PHOTO_DATA["leehyunjeong_3"],
      PHOTO_DATA["leehyunjeong_4"],
    ],
    bgClass: 'ac-bg-3',
    specs: [
      { label: '신장', value: '163 cm' },
      { label: '생년', value: '1996년생' },
      { label: '특기', value: '경상도사투리, 수화' },
      { label: '학력', value: '동아방송대학 연기과' },
    ],
    filmo: [
      { year: '2026', title: '드라마', platform: '방영예정' },
      { year: '2025', title: '드라마', platform: '방영작' },
    ],
    ads: [
      { year: '2026', title: '화보 촬영', platform: '화보' },
    ],
  },
  ryujiyeon: {
    number: '04',
    nameKo: '류지연',
    nameEn: 'RYU JIYEON',
    photos: [
      PHOTO_DATA["ryujiyeon_1"],
      PHOTO_DATA["ryujiyeon_2"],
      PHOTO_DATA["ryujiyeon_3"],
      PHOTO_DATA["ryujiyeon_4"],
    ],
    bgClass: 'ac-bg-4',
    specs: [
      { label: '신장', value: '163 cm' },
      { label: '생년', value: '2000년생' },
      { label: '특기', value: '수영, 치어리딩, 펜싱, 댄스' },
      { label: '학력', value: '서울예술고등학교' },
    ],
    filmo: [
      { year: '2026', title: '가족계획2', platform: 'Coupang Play' },
      { year: '2026', title: '내 아내는 8살', platform: 'Topreels' },
      { year: '2022', title: '구조', platform: '영화' },
      { year: '2021', title: '발레리나', platform: '영화' },
      { year: '2021', title: '어른연습생', platform: 'TVING' },
      { year: '2020', title: '연애혁명', platform: '카카오TV' },
      { year: '2020', title: '달고나', platform: '웹드라마' },
      { year: '2020', title: '히트맨', platform: '영화' },
      { year: '2019', title: '리얼타임러브 1,2', platform: '웹드라마' },
      { year: '2018', title: '신의퀴즈 리부트', platform: 'OCN' },
      { year: '2018', title: '기억하리2', platform: '투니버스' },
      { year: '2016', title: '윤정', platform: '영화' },
    ],
    ads: [],
  },
  jinhyuk: {
    number: '05',
    nameKo: '진혁',
    nameEn: 'JIN HYUK',
    photos: [
      PHOTO_DATA["jinhyuk_1"],
      PHOTO_DATA["jinhyuk_2"],
      PHOTO_DATA["jinhyuk_3"],
    ],
    bgClass: 'ac-bg-5',
    specs: [
      { label: '신장', value: '183 cm' },
      { label: '생년', value: '1987년생' },
      { label: '특기', value: '수영, 골프, 기타, 노래, 그림' },
    ],
    filmo: [
      { year: '2024', title: '페이스미', platform: 'KBS' },
      { year: '2022', title: '조선정신과의사 유세풍', platform: 'tvN' },
      { year: '2021', title: '우리는 이별에 서툴러서', platform: '영화' },
      { year: '2020', title: '뜨거운피', platform: '영화' },
      { year: '2019', title: '오후의 로맨틱한 라디오', platform: '웹드라마' },
      { year: '2019', title: '퍼펙트맨', platform: '영화' },
      { year: '2017', title: '블랙', platform: 'OCN' },
      { year: '2016', title: '운빨로맨스', platform: 'MBC' },
      { year: '2016', title: '뷰티학개론', platform: 'Olive tv' },
      { year: '2014', title: '쓰리데이즈', platform: 'SBS' },
      { year: '2013', title: '출생의 비밀', platform: 'SBS' },
      { year: '2012', title: '보고싶다', platform: 'MBC' },
    ],
    ads: [
      { year: '2021', title: '광고 활동', platform: 'CF' },
      { year: '2020', title: '광고 활동', platform: 'CF' },
      { year: '2019', title: '광고 활동', platform: 'CF' },
    ],
  },
  leekyoungjae: {
    number: '06',
    nameKo: '이경재',
    nameEn: 'LEE KYOUNG JAE',
    photos: [
      PHOTO_DATA["leekyoungjae_1"],
      PHOTO_DATA["leekyoungjae_2"],
      PHOTO_DATA["leekyoungjae_3"],
      PHOTO_DATA["leekyoungjae_4"],
    ],
    bgClass: 'ac-bg-6',
    specs: [
      { label: '신장', value: '182 cm' },
      { label: '생년', value: '1994년생' },
      { label: '특기', value: '전라도사투리, 수영, 축구' },
      { label: '학력', value: '대덕대학교 모델과' },
    ],
    filmo: [
      { year: '2026', title: '프로젝트Y', platform: '영화' },
      { year: '2023', title: '이머시브씨어터 카지노', platform: '연극' },
      { year: '2021', title: '귀문', platform: '영화' },
      { year: '2021', title: '드림', platform: '영화' },
      { year: '2020', title: '미씽: 그들이 있었다', platform: 'OCN' },
      { year: '2020', title: '굿캐스팅', platform: 'SBS' },
    ],
    ads: [],
  },
  leegunhee: {
    number: '07',
    nameKo: '이건희',
    nameEn: 'LEE GUNHEE',
    photos: [
      PHOTO_DATA["leegunhee_1"],
      PHOTO_DATA["leegunhee_2"],
      PHOTO_DATA["leegunhee_3"],
      PHOTO_DATA["leegunhee_4"],
    ],
    bgClass: 'ac-bg-7',
    specs: [
      { label: '신장', value: '188 cm' },
      { label: '생년', value: '1992년생' },
      { label: '특기', value: '노래, 축구, 복싱' },
      { label: '학력', value: '순천향대학교 스포츠의학과' },
    ],
    filmo: [
      { year: '2023', title: '소년시대', platform: 'Coupang Play' },
      { year: '2022', title: '사장님을 잠금해제', platform: 'ENA' },
      { year: '2017', title: '죽어야사는남자', platform: 'MBC' },
      { year: '2015', title: '아름다운 당신', platform: 'MBC' },
      { year: '2015', title: '리멤버', platform: 'SBS' },
    ],
    ads: [
      { year: '2022', title: 'TENNIS UNIVERSITY', platform: 'CF' },
      { year: '2021', title: 'BANG BANG', platform: 'CF' },
      { year: '2018', title: '맥도날드 평창', platform: 'CF' },
      { year: '2018', title: '맥심 플랜트', platform: 'CF' },
      { year: '2018', title: '요기요', platform: 'CF' },
      { year: '2018', title: 'Galaxy Note9', platform: 'CF' },
    ],
  },

  hanareun: {
    number: '08',
    nameKo: '한아름',
    nameEn: 'HAN A REUM',
    photos: [
      PHOTO_DATA["hanareun_1"],
      PHOTO_DATA["hanareun_2"],
      PHOTO_DATA["hanareun_3"],
    ],
    bgClass: 'ac-bg-8',
    specs: [
      { label: '신장', value: '167 cm' },
      { label: '생년', value: '1995년생' },
      { label: '특기', value: '노래, 작곡, 피아노, 한국무용, 액션, 민요, 필라테스' },
      { label: '학력', value: '가천대학교 연기예술학과 수석졸업' },
    ],
    filmo: [
      { year: '2026', title: '위대한방옥숙', platform: 'tvN' },
      { year: '2025', title: '얄미운사랑', platform: 'tvN' },
      { year: '2025', title: '화려한날들', platform: 'KBS' },
      { year: '2025', title: '서울에 삽니다 시즌2+', platform: '웹드라마 주연' },
      { year: '2024', title: '돌풍', platform: 'Netflix' },
      { year: '2024', title: '웨딩임파서블', platform: 'tvN' },
      { year: '2024', title: '심하율은 방송중', platform: '웹드라마 주연' },
      { year: '2024', title: '뒤주', platform: '영화' },
      { year: '2023', title: '사랑의 이해', platform: 'JTBC' },
      { year: '2023', title: '변론을 시작하겠습니다', platform: 'Disney+' },
      { year: '2023', title: '밑도 끝도 없이, 너다', platform: 'Disney+' },
      { year: '2022', title: '내일', platform: 'MBC' },
      { year: '2022', title: '안녕하세요', platform: '영화' },
      { year: '2022', title: 'MBTI to US', platform: '웹드라마 주연' },
      { year: '2020', title: '오케이마담', platform: '영화' },
      { year: '2019', title: '두번할까요', platform: '영화' },
      { year: '2018', title: '창궐', platform: '영화' },
      { year: '2018', title: '안시성', platform: '영화' },
    ],
    ads: [],
  },
};